services:
  - type: web
    name: elms
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn elms.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: elms.settings
      - key: PYTHON_VERSION
        value: 3.10
